### PR TITLE
Vignette edits

### PR DESCRIPTION
**Pull request by mblue9**
I expanded the vignette a bit what do you think?
Also applied the Bioconductor styling.

### CODE REVIEW

**Comment by mblue9** [comment]
By the way I noticed `arrange` isn't included even though the vignette says all dplyr APIs are available. Is arrange intentionally excluded or is it by accident?

**Comment by stemangiola** [comment]
> 
> 
> By the way I noticed `arrange` isn't included even though the vignette says all dplyr APIs are available. Is arrange intentionally excluded or is it by accident?

Very good eye! arrange is a bit complex for SE object if it even makes sense, so I skept it for the moment. Which makes that claim not true. We could say "vast majority" :)

**Review by stemangiola — APPROVED** [review]

**Comment by mblue9** [comment]
>Very good eye! arrange is a bit complex for SE object if it even makes sense, so I skept it for the moment. Which makes that claim not true. We could say "vast majority" :)

Ok that's fine, I only noticed because I tried to include it in the vignette and it didn't work 😄  
It was for this as I thought it would be handy to sort by the values
```
pasilla_tidy %>%
    group_by(sample) %>%
    summarise(total_counts=sum(counts)) %>%
    arrange(total_counts)
```
But it could be added later if people want it and it's possible. 
Could be good to make it clear what functions are included (like [here](https://github.com/martijnvanattekum/cleanse)) ?or not included if that's easier?

**Comment by mblue9** [comment]
I've changed to `almost all` as it's shorter than `vast majority of` :) 
I did it for tidyr too just in case but it that right? 
What do you think?

**Comment by mblue9** [comment]
Cool. Was wondering ..do you have to do a push to Bioconductor after merging to master or does Bioconductor automatically detect when you've merged to master?

**Comment by stemangiola** [comment]
> e to do a push to Biocond

version up triggers their integration. Feel free also to up the version directly on master.

**Comment by mblue9** [comment]
Ok will do. What about this though I just saw it in the email you forwarded this morning
```
Remember: if you submitted your package after July 7th, 2020,
when making changes to your repository push to
git@git.bioconductor.org:packages/tidySE to trigger a new build.
A quick tutorial for setting up remotes and pushing to upstream can be found here.
```
Does that mean a push is now needed after the version change?

**Comment by stemangiola** [comment]
> 
> 
> Ok will do. What about this though I just saw it in the email you forwarded this morning
> 
> ```
> Remember: if you submitted your package after July 7th, 2020,
> when making changes to your repository push to
> git@git.bioconductor.org:packages/tidySE to trigger a new build.
> A quick tutorial for setting up remotes and pushing to upstream can be found here.
> ```
> 
> Does that mean a push is now needed after the version change?

Aaaa. Done!

**Comment by mblue9** [comment]
Ok great 😄 One other thing the website https://stemangiola.github.io/tidySE/ isn't working.. do you need to enable Github Pages for this repo?

**Comment by stemangiola** [comment]
> 
> 
> Ok great 😄 One other thing the website https://stemangiola.github.io/tidySE/ isn't working.. do you need to enable Github Pages for this repo?

Done. Too many repooos! XD

**Pull request merged**
