### PR TITLE
Tcga maria

### PR DESCRIPTION
**Pull request by stemangiola**

### CODE REVIEW

**Comment by stemangiola** [comment]
Hello @mblue9, when you have time, could you please check this branch with your SE-TCGA workshop. Do you still experience very long waiting times, and where?

Thanks!

**Comment by stemangiola** [comment]
Hello @mblue9, any chance to benchmark this?

I noticed the downloads of tidySE are going down while the ones for tidybulk are going up. I am wondering if this is for efficiency reasons. :(

**Comment by mblue9** [comment]
I just tried with this branch and seems to be similar to before (e.g. master). If I do 

`counts_se %>% select(barcode)`

after about 3 mins I get

`Error: vector memory exhausted (limit reached?)`

maybe as it goes up to 16GB RAM used and that's all I have on my laptop?

If you want to see, counts SE object is [here](https://unimelbcloud-my.sharepoint.com/:u:/g/personal/maria_doyle_unimelb_edu_au/EQHhVA_mSahOtvTislIqZfABWLauBPUA8b-nIrW7eDnTLQ?e=jccDoU)
Object was created with 
```
library(TCGAbiolinks)
query <- GDCquery(project = "TCGA-BRCA",
                           data.category = "Gene expression",
                           data.type = "Gene expression quantification",
                           platform = "Illumina HiSeq", 
                           file.type  = "normalized_results",
                           experimental.strategy = "RNA-Seq",
                           legacy = TRUE)
GDCdownload(query, method = "api", files.per.chunk = 10)
counts_se <- GDCprepare(query)
#save. object
saveRDS(counts_se, "tcgabiolinks_counts_se.rds", compress="xz")
```

**Comment by stemangiola** [comment]
It should not do this. Let me try

**Comment by stemangiola** [comment]
> counts_se %>% select(barcode)

Hello Maria, it sounds very strange.On my local machine I get

```r
> library(tictoc)
> tic()
> counts_se |> select(barcode)
tidySummarizedExperiment says: Key columns are missing. A data frame is returned for independent data analysis.
# A tibble: 24,235,605 x 1
   barcode                     
   <chr>                       
 1 TCGA-GM-A2DN-01A-11R-A180-07
 2 TCGA-GM-A2DN-01A-11R-A180-07
 3 TCGA-GM-A2DN-01A-11R-A180-07
 4 TCGA-GM-A2DN-01A-11R-A180-07
 5 TCGA-GM-A2DN-01A-11R-A180-07
 6 TCGA-GM-A2DN-01A-11R-A180-07
 7 TCGA-GM-A2DN-01A-11R-A180-07
 8 TCGA-GM-A2DN-01A-11R-A180-07
 9 TCGA-GM-A2DN-01A-11R-A180-07
10 TCGA-GM-A2DN-01A-11R-A180-07
# ... with 24,235,595 more rows
> toc()
2.23 sec elapsed
```

With my object being

```r
> counts_se 
# A SummarizedExperiment-tibble abstraction: 24,235,605 x 97
# Transcripts=19947 | Samples=1215 | Assays=normalized_count
   .feature .sample normalized_count barcode patient sample shortLetterCode definition sample_submitte~ sample_type_id sample_id sample_type days_to_collect~ state
   <chr>    <chr>              <dbl> <chr>   <chr>   <chr>  <chr>           <chr>      <chr>            <chr>          <chr>     <chr>                  <int> <chr>
 1 A1BG     TCGA-G~          118.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 2 A2M      TCGA-G~        14980.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 3 NAT1     TCGA-G~         1638.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 4 NAT2     TCGA-G~            1.54  TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 5 RP11-98~ TCGA-G~        52000.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 6 AADAC    TCGA-G~            0.771 TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 7 AAMP     TCGA-G~         2356.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 8 AANAT    TCGA-G~            0.386 TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
 9 AARS     TCGA-G~         2048.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
10 ABAT     TCGA-G~         2243.    TCGA-G~ TCGA-G~ TCGA-~ TP              Primary s~ TCGA-GM-A2DN-01A 01             e46b29b9~ Primary Tu~             2436 rele~
# ... with 42 more rows, and 83 more variables: initial_weight <dbl>, preservation_method <chr>, pathology_report_uuid <chr>, submitter_id <chr>,
#   oct_embedded <chr>, days_to_sample_procurement <int>, is_ffpe <lgl>, tissue_type <chr>, synchronous_malignancy <chr>, ajcc_pathologic_stage <chr>,
#   tumor_stage <chr>, days_to_diagnosis <int>, treatments <I<list>>, last_known_disease_status <chr>, tissue_or_organ_of_origin <chr>,
#   days_to_last_follow_up <int>, primary_diagnosis <chr>, age_at_diagnosis <int>, prior_malignancy <chr>, year_of_diagnosis <int>, prior_treatment <chr>,
#   ajcc_staging_system_edition <chr>, ajcc_pathologic_t <chr>, morphology <chr>, ajcc_pathologic_n <chr>, ajcc_pathologic_m <chr>, classification_of_tumor <chr>,
#   diagnosis_id <chr>, icd_10_code <chr>, site_of_resection_or_biopsy <chr>, tumor_grade <chr>, progression_or_recurrence <chr>, alcohol_history <chr>,
#   exposure_id <chr>, race <chr>, ethnicity <chr>, gender <chr>, vital_status <chr>, age_at_index <int>, days_to_birth <int>, year_of_birth <int>,
#   demographic_id <chr>, year_of_death <int>, days_to_death <int>, bcr_patient_barcode <chr>, primary_site <I<list>>, project_id <chr>, disease_type <I<list>>,
#   name <chr>, releasable <lgl>, released <lgl>, paper_patient <chr>, paper_Tumor.Type <chr>, paper_Included_in_previous_marker_papers <chr>,
#   paper_vital_status <chr>, paper_days_to_birth <chr>, paper_days_to_death <chr>, paper_days_to_last_followup <chr>,
#   paper_age_at_initial_pathologic_diagnosis <dbl>, paper_pathologic_stage <chr>, paper_Tumor_Grade <chr>, paper_BRCA_Pathology <chr>,
#   paper_BRCA_Subtype_PAM50 <chr>, paper_MSI_status <chr>, paper_HPV_Status <chr>, paper_tobacco_smoking_history <chr>, `paper_CNV Clusters` <chr>,
#   `paper_Mutation Clusters` <chr>, `paper_DNA.Methylation Clusters` <chr>, `paper_mRNA Clusters` <chr>, `paper_miRNA Clusters` <chr>, `paper_lncRNA
#   Clusters` <chr>, `paper_Protein Clusters` <chr>, `paper_PARADIGM Clusters` <chr>, `paper_Pan-Gyn Clusters` <chr>, gene_id <chr>, entrezgene <int>,
#   ensembl_gene_id <chr>, seqnames <fct>, start <int>, end <int>, width <int>, strand <fct>
```

If you do 

```r
debugonce(select)

counts_se |> select(barcode)
```

You pass the generic method (clicking enter twice) and you go into the tidySE method do you see this function?

```r
select.SummarizedExperiment <- function(.data, ...) {
   
  
  
  # colnames_col <- get_colnames_col(.data)
  # colnames_row <- get_rownames_col(.data)
  # colnames_assay = .data@assays@data %>% names
  

  
  # Deprecation of special column names
  if(is_sample_feature_deprecated_used(
    .data, 
    (enquos(..., .ignore_empty = "all") %>% map(~ quo_name(.x)) %>% unlist)
  )){
    .data= ping_old_special_column_into_metadata(.data)
  }
  
  # See if join done by sample, feature or both
  columns_query = 
    .data %>%
    .[1,1, drop=FALSE] %>% 
    as_tibble() %>% 
    select_helper(...) %>% 
    colnames()
  
  row_data_tibble = 
    rowData(.data) %>% 
    as_tibble(rownames = f_(.data)$name) 
  
  row_data_DF =
    row_data_tibble %>% 
    select(one_of(columns_query), !!f_(.data)$symbol) %>%
    suppressWarnings() %>% 
    data.frame(row.names=pull(., !!f_(.data)$symbol)) %>%
    select(-!!f_(.data)$symbol) %>%
    DataFrame()
  
  col_data_tibble = 
    colData(.data) %>% 
    as_tibble(rownames = s_(.data)$name) 
  
  col_data_DF = 
    col_data_tibble %>%  
    select(one_of(columns_query), !!s_(.data)$symbol) %>%
    suppressWarnings() %>% 
    data.frame(row.names=pull(., !!s_(.data)$symbol)) %>%
    select(-!!s_(.data)$symbol) %>%
    DataFrame()
  
  count_data = 
    assays(.data)@listData %>% .[names(assays(.data)@listData) %in% columns_query]
  
  columns_query %>%
    when(
      
      # If it's just col data
     ncol(row_data_DF) == 0 & !f_(.data)$name %in% columns_query & length(count_data) == 0 & ( ncol(col_data_DF) > 0 | s_(.data)$name %in% columns_query)  ~ {
       message("tidySummarizedExperiment says: Key columns are missing. A data frame is returned for independent data analysis.")
       
       col_data_tibble %>% 
         select_helper(...) %>% 
         slice(rep(1:n(), each=nrow(!!.data) ))
          
        },
      
     # If it's just row data
     ncol(col_data_DF) == 0 & !s_(.data)$name %in% columns_query & length(count_data) == 0 & ( ncol(row_data_DF) > 0 | f_(.data)$name %in% columns_query) ~ {
       message("tidySummarizedExperiment says: Key columns are missing. A data frame is returned for independent data analysis.")
       
       row_data_tibble %>% 
         select_helper(...) %>% 
         slice(rep(1:n(), ncol(!!.data)  ))
       
     },
     
     
     !all(c(get_needed_columns(.data)) %in% .)  ~ {
       if(ncol(.data)>100) message("tidySummarizedExperiment says: You are doing a complex selection both sample-wise and feature-wise. In the latter case, for efficiency (until further development), it is better to separate your selects sample-wise OR feature-wise.")
       message("tidySummarizedExperiment says: Key columns are missing. A data frame is returned for independent data analysis.")
       
       .data %>%
         as_tibble(skip_GRanges = T) %>%
         select_helper(...) 
     },
  
    ~ {
      rowData(.data) = row_data_DF
      colData(.data) = col_data_DF
      assays(.data) = count_data
      .data
      
    } 
    )
  # ,
  #     
  #     ~ stop("tidySummarizedExperiment says: ERROR FOR DEVELOPERS: this option should not exist. In join utility.")
  #     
  #   )
   
}

```

I want to make sure you are working with the right version/branch of tidySE

**Comment by mblue9** [comment]
Ah sorry I did install this branch fresh yesterday but maybe somehow an old tidySE version was loaded. This works great now, lighting fast! ⚡ 👏

**Comment by stemangiola** [comment]
> Ah sorry I did install this branch fresh yesterday but maybe somehow an old tidySE version was loaded. This works great now, lighting fast! ⚡ 👏

Great, you made me jump before!

Can you tell me what function in your TCGA workshop you are unhappy about?

It would be nice to run your workshop with or without `as_tibble() %>% as_tidybulk()` and see who wins ;)

I mean that could be another blog post!

**Comment by mblue9** [comment]
Ok I'm doing some more testing now.
join was a function giving me issues before, I tried that and it's super fast. But something weird is if I join with the full counts_se object it's lightning fast but if I select a few columns then join it's really slow. 

```
library(tictoc)
tic()
tcga_joined <- inner_join(counts_se, tcga_her2, by = c("patient" = "bcr_patient_barcode"))
toc()
0.215 sec elapsed
```

```
counts_small <- counts_se %>% 
select(.feature, .sample, normalized_count, patient)
tic()
tcga_joined <- inner_join(counts_small, tcga_her2, by = c("patient" = "bcr_patient_barcode"))
tidySummarizedExperiment says: if you are joining a dataframe both sample-wise and feature-wise, for efficiency (until further development), it is better to separate your joins and join datasets sample-wise OR feature-wise.
tidySummarizedExperiment says: This operation lead to duplicated feature names. A data frame is returned for independent data analysis.
tidySummarizedExperiment says: A data frame is returned for independent data analysis.
toc()
88.1 sec elapsed
```

Digging a bit further, something weird seems to be happening with the column selection e.g.`select(.sample)` works, `select(.sample, .feature)` doesn't, see below
```
counts_se %>% 
+     select(.sample)
tidySummarizedExperiment says: Key columns are missing. A data frame is returned for independent data analysis.
# A tibble: 24,235,605 × 1
   .sample                     
   <chr>                       
 1 TCGA-GM-A2DN-01A-11R-A180-07
 2 TCGA-GM-A2DN-01A-11R-A180-07
 3 TCGA-GM-A2DN-01A-11R-A180-07
 4 TCGA-GM-A2DN-01A-11R-A180-07
 5 TCGA-GM-A2DN-01A-11R-A180-07
 6 TCGA-GM-A2DN-01A-11R-A180-07
 7 TCGA-GM-A2DN-01A-11R-A180-07
 8 TCGA-GM-A2DN-01A-11R-A180-07
 9 TCGA-GM-A2DN-01A-11R-A180-07
10 TCGA-GM-A2DN-01A-11R-A180-07
# … with 24,235,595 more rows
> counts_se %>% 
+     select(.feature, .sample)
# A SummarizedExperiment-tibble abstraction: 24,235,605 × 7
# Transcripts=19947 | Samples=1215 | Assays=
   .feature     .sample        seqnames   start    end  width strand
   <chr>        <chr>          <fct>      <int>  <int>  <int> <fct> 
 1 A1BG         TCGA-GM-A2DN-… chr19     5.89e7 5.89e7   8322 -     
 2 A2M          TCGA-GM-A2DN-… chr12     9.22e6 9.27e6  48566 -     
 3 NAT1         TCGA-GM-A2DN-… chr8      1.80e7 1.81e7  53213 +     
 4 NAT2         TCGA-GM-A2DN-… chr8      1.82e7 1.83e7   9974 +     
 5 RP11-986E7.7 TCGA-GM-A2DN-… chr14     9.51e7 9.51e7  32589 +     
 6 AADAC        TCGA-GM-A2DN-… chr3      1.52e8 1.52e8  14452 +     
 7 AAMP         TCGA-GM-A2DN-… chr2      2.19e8 2.19e8   6131 -     
 8 AANAT        TCGA-GM-A2DN-… chr17     7.44e7 7.45e7  16767 +     
 9 AARS         TCGA-GM-A2DN-… chr16     7.03e7 7.03e7  37249 -     
10 ABAT         TCGA-GM-A2DN-… chr16     8.77e6 8.88e6 110011 +     
# … with 42 more rows
```

**Comment by stemangiola** [comment]
> Ok I'm doing some more testing now.
> join was a function giving me issues before, I tried that and it's super fast. But something weird is if I join with the full counts_se object it's lightning fast but if I select a few columns then join it's really slow.

Solved this bug, please reinstall


> Digging a bit further, something weird seems to be happening with the column selection e.g.`select(.sample)` works, `select(.sample, .feature)` doesn't, see below

Here the first query lead to a invalid SE and results in a tibble, the second leads to a valid SE and all other read-only information is carried on as well. I know pretty confusing.

I am thinking we should use the tidyverse `cli` for color coding the columns 
- that are key (sample, feature)
- that you can change (all rest)
- read only (e.g. granges)

**Comment by mblue9** [comment]
>Solved this bug, please reinstall

I did and retried, works great now 👍 

>>Digging a bit further, something weird seems to be happening with the column selection e.g.select(.sample) works, select(.sample, .feature) doesn't, see below

>Here the first query lead to a invalid SE and results in a tibble, the second leads to a valid SE and all other read-only information is carried on as well. I know pretty confusing.

>I am thinking we should use the tidyverse cli for color coding the columns

>that are key (sample, feature)
>that you can change (all rest)
>read only (e.g. granges)

Yes that was confusing to me. So if you select both .sample and .feature you get SE otherwise you get tibble? Colour coding could be good.                     

Was just seeing what happens with airway dataset and in that case I get a GRangesList instead of the columns (`seqnames   start    end  width strand`) l get with the tcga data above, is that expected? seems strange they work differently?
```
airway %>% select(.sample, .feature)
# A SummarizedExperiment-tibble abstraction: 512,816 × 3
# Transcripts=64102 | Samples=8 | Assays=
   .feature        .sample    GRangesList      
   <chr>           <chr>      <list>           
 1 ENSG00000000003 SRR1039508 <tibble [17 × 8]>
 2 ENSG00000000005 SRR1039508 <tibble [10 × 8]>
```

**Comment by stemangiola** [comment]
> Was just seeing what happens with airway dataset and in that case I get a GRangesList instead of the columns (`seqnames start end width strand`) l get with the tcga data above, is that expected? seems strange they work differently?

This is because each list of ranges for each gene cannot be represented in a row. Before was all nested but users told be that in case of only one range they would like to see it in explicit exploded format.

Hard to know what is best. I haven't received enough feedback.

**Comment by stemangiola** [comment]
Hello @mblue9 do you think it is safe to merge, do you think it is good for your case studies?

**Comment by mblue9** [comment]
I think it is but if you want I can look at this again next week and let you know

**Comment by stemangiola** [comment]
> I think it is but if you want I can look at this again next week and let you know

I merge, and if you can a last check at the same time would be amazing, as there are a _lot_ of changes ;)

**Pull request merged**
