### PR TITLE
Group split

### PR DESCRIPTION
**Pull request by B0ydT**
Issue #75

### CODE REVIEW

**Comment by B0ydT** [comment]
Let me know if you want the version number incremented, I'm not sure what the criteria are for that. There is a tidyselect warning from the tests, but I think that is being raised in another function.

**Comment by B0ydT** [comment]
There seems to be an issue running the examples, it tries to use `dplyr::group_split` instead. I'm not sure if this is because I had to explicitly export `@export group_split.SummarizedExperiment` in order to get the function to build at all.

**Comment by B0ydT** [comment]
Ignore that last comment, should be fine now

**Comment by stemangiola** [comment]
Congrats @B0ydT sorry for the delay. Would you be interested in proposing your PR for tidySCE and/or tidySeurat?

**Pull request merged**
